#!/usr/bin/env python3
"""Prepare the unified training package for all Vast.ai tracks.

Reads existing COCO JSON annotations and:
1. Converts them to YOLO TXT format for Track A/E/F
2. Creates dataset.yaml for Ultralytics
3. Verifies all files are consistent

Usage:
    uv run python scripts/vastai_prepare_all_tracks.py
"""
from __future__ import annotations

import json
from pathlib import Path

CLIENT_ROOT = Path(__file__).resolve().parents[1]
DATASET_DIR = CLIENT_ROOT / "blob" / "kaggle_dataset"


def coco_to_yolo_labels(ann_path: Path, output_dir: Path) -> int:
    """Convert a COCO JSON annotation file to YOLO TXT label files.

    COCO bbox format: [x_top_left, y_top_left, width, height] (absolute pixels)
    YOLO format: class_id x_center y_center width height (normalized 0-1)

    Returns the number of label files written.
    """
    with open(ann_path) as f:
        coco = json.load(f)

    # Build category mapping: COCO category_id -> 0-based YOLO class_id
    cat_id_to_yolo = {}
    for i, cat in enumerate(sorted(coco["categories"], key=lambda c: c["id"])):
        cat_id_to_yolo[cat["id"]] = i

    # Build image_id -> image info mapping
    images = {img["id"]: img for img in coco["images"]}

    # Group annotations by image_id
    anns_by_image: dict[int, list[dict]] = {}
    for ann in coco["annotations"]:
        anns_by_image.setdefault(ann["image_id"], []).append(ann)

    output_dir.mkdir(parents=True, exist_ok=True)
    written = 0

    for img_id, img_info in images.items():
        w = img_info["width"]
        h = img_info["height"]
        filename = img_info["file_name"]
        label_name = Path(filename).stem + ".txt"

        lines = []
        for ann in anns_by_image.get(img_id, []):
            class_id = cat_id_to_yolo[ann["category_id"]]
            bx, by, bw, bh = ann["bbox"]  # COCO: x,y,w,h absolute

            # Convert to YOLO: x_center, y_center, width, height (normalized)
            x_center = (bx + bw / 2.0) / w
            y_center = (by + bh / 2.0) / h
            nw = bw / w
            nh = bh / h

            # Clamp to [0, 1]
            x_center = max(0.0, min(1.0, x_center))
            y_center = max(0.0, min(1.0, y_center))
            nw = max(0.0, min(1.0, nw))
            nh = max(0.0, min(1.0, nh))

            lines.append(f"{class_id} {x_center:.6f} {y_center:.6f} {nw:.6f} {nh:.6f}")

        label_path = output_dir / label_name
        label_path.write_text("\n".join(lines) + ("\n" if lines else ""))
        written += 1

    return written


def create_dataset_yaml(dataset_dir: Path) -> Path:
    """Create Ultralytics dataset.yaml."""
    yaml_content = """# Ultralytics YOLO dataset config
# Auto-generated by vastai_prepare_all_tracks.py

path: /workspace/dataset
train: images/train
val: images/val
test: images/test

nc: 1
names: ['piece']
"""
    yaml_path = dataset_dir / "dataset.yaml"
    yaml_path.write_text(yaml_content)
    return yaml_path


def verify_consistency(dataset_dir: Path) -> dict[str, dict]:
    """Verify that images, COCO JSON, and YOLO labels are consistent."""
    stats = {}
    for split in ["train", "val", "test"]:
        img_dir = dataset_dir / "images" / split
        ann_path = dataset_dir / "annotations" / f"{split}.json"
        label_dir = dataset_dir / "labels_yolo" / split

        images = sorted(img_dir.glob("*.jpg")) + sorted(img_dir.glob("*.png"))
        labels = sorted(label_dir.glob("*.txt")) if label_dir.exists() else []

        with open(ann_path) as f:
            coco = json.load(f)

        image_stems = {p.stem for p in images}
        label_stems = {p.stem for p in labels}

        missing_labels = image_stems - label_stems
        extra_labels = label_stems - image_stems

        stats[split] = {
            "images": len(images),
            "coco_images": len(coco["images"]),
            "coco_annotations": len(coco["annotations"]),
            "yolo_labels": len(labels),
            "missing_labels": len(missing_labels),
            "extra_labels": len(extra_labels),
        }

    return stats


def main():
    print(f"Dataset directory: {DATASET_DIR}")

    # Verify COCO annotations exist
    for split in ["train", "val", "test"]:
        ann_path = DATASET_DIR / "annotations" / f"{split}.json"
        if not ann_path.exists():
            raise SystemExit(f"Missing annotation file: {ann_path}")
        img_dir = DATASET_DIR / "images" / split
        if not img_dir.exists():
            raise SystemExit(f"Missing image directory: {img_dir}")

    # Step 1: Convert COCO to YOLO labels
    print("\n=== Converting COCO JSON to YOLO TXT labels ===")
    for split in ["train", "val", "test"]:
        ann_path = DATASET_DIR / "annotations" / f"{split}.json"
        label_dir = DATASET_DIR / "labels_yolo" / split
        count = coco_to_yolo_labels(ann_path, label_dir)
        print(f"  {split}: wrote {count} label files")

    # Step 2: Create dataset.yaml
    print("\n=== Creating dataset.yaml ===")
    yaml_path = create_dataset_yaml(DATASET_DIR)
    print(f"  Written to: {yaml_path}")

    # Step 3: Verify consistency
    print("\n=== Verification ===")
    stats = verify_consistency(DATASET_DIR)
    all_ok = True
    for split, s in stats.items():
        ok = s["missing_labels"] == 0 and s["extra_labels"] == 0 and s["images"] == s["yolo_labels"]
        status = "OK" if ok else "MISMATCH"
        if not ok:
            all_ok = False
        print(f"  {split}: {s['images']} images, {s['coco_annotations']} COCO anns, "
              f"{s['yolo_labels']} YOLO labels - {status}")
        if s["missing_labels"]:
            print(f"    WARNING: {s['missing_labels']} images without YOLO labels")
        if s["extra_labels"]:
            print(f"    WARNING: {s['extra_labels']} extra YOLO labels without images")

    if all_ok:
        print("\nAll checks passed.")
    else:
        print("\nWARNING: Some checks failed, review above.")

    # Print sample YOLO label
    print("\n=== Sample YOLO label ===")
    sample_labels = list((DATASET_DIR / "labels_yolo" / "train").glob("*.txt"))
    if sample_labels:
        sample = sample_labels[0]
        content = sample.read_text().strip()
        print(f"  {sample.name}:")
        for line in content.split("\n")[:3]:
            print(f"    {line}")

    print(f"\nDataset ready at: {DATASET_DIR}")


if __name__ == "__main__":
    main()
