// Laser-cut sheet parts for the machine — flat DXFs cut from plywood.
//
// Unlike the 3D printed parts these don't go through the slicer pipeline;
// the DXFs live in static/dxf/ and their SVG previews are generated by
// slicer/dxf_preview.py (re-run it when a DXF changes). The DATA lives in
// slicer/parts.json (kind: 'lasercut') and rides through the generated JSON
// so the docs site renders the same records; this module is the typed view.

import raw from '$lib/data/catalog.generated.json';

export type LaserCutPart = {
	id: string;
	name: string;
	// context photo (bucket URL); the docs site's parts-needed cards use this,
	// while this app shows the DXF outline preview
	photo?: string;
	caption?: string; // small text under the docs card
	assembly?: string; // grouping label, e.g. the two cage pieces
	description: string;
	// expected stock thickness, quoted both ways since sheets are sold in imperial
	// but cut/modeled in metric (nearest full mm)
	thicknessIn: string; // e.g. '3/8″'
	thicknessMm: number; // nearest full-mm equivalent
	widthMm: number; // bounding box of the cut, from dxf_preview.py
	heightMm: number;
	qty: number; // per machine
	onshape: string; // pinned OnShape version this DXF was exported from
	dxf: string; // download path
	preview: string; // SVG outline preview path
	updated: string; // date of the DXF export (ISO)
	// optional "by hand" (jigsaw + drill) route for people without a laser
	handcut?: {
		guide: 'top-plate' | 'cage-top' | 'cage-bottom'; // which guide component to open
		blurb: string; // the "By hand" tab paragraph
		stock: string; // stock size, shown on the tab
		tools: string; // tools line, shown on the tab
	};
};

export const LASER_CUT_PARTS = ((raw as Record<string, unknown>).lasercut ??
	[]) as LaserCutPart[];
