"""add extra_metadata to samples

Revision ID: 8d8fe12f5fb5
Revises: 0f3b104c89eb
Create Date: 2026-04-01 13:29:28.410674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8d8fe12f5fb5'
down_revision: Union[str, None] = '0f3b104c89eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'extra_metadata')
    # ### end Alembic commands ###
