#!/usr/bin/env python3
"""Generate the "Seltenes und Besonderes" secondary sorting profile.

Reads a Rebrickable CSV dump (colors, part_categories, parts, sets,
inventories, inventory_parts) and writes

- the profile JSON in the shape of ``POST /api/profiles/{id}/versions``
  (``SortingProfileVersionCreateRequest``): one filter rule per target
  category, every rule tagged ``role: "secondary"``, in bin-priority order;
- a markdown summary with what each rule matches in the CSVs and what the
  rule engine cannot express.

The CSVs stay where they are; pass their directory:

    uv run scripts/generate_secondary_profile.py /tmp/rb \\
        --out /tmp/seltenes-und-besonderes.json

Rarity is not a rule-engine field, so the rare rule is baked as a
``part_num in [...]`` list from the inventories. Regenerate after a CSV
refresh to keep it current.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Any

csv.field_size_limit(10**9)

PROFILE_NAME = "Seltenes und Besonderes"
PROFILE_DESCRIPTION = (
    "Secondary profile: side-sorts printed, minifig, transparent, metallic, "
    "wheel, special Technic and rare parts. Generated by "
    "scripts/generate_secondary_profile.py from the Rebrickable CSVs."
)
DEFAULT_CATEGORY_ID = "misc"

# Rebrickable part_categories ids.
CAT_MINIFIG_HEADS = [59, 62]
CAT_MINIFIG_TORSOS = [60, 63]
CAT_MINIFIG_LEGS = [61, 64]
CAT_MINIFIG_ACCESSORIES = [27, 65, 70, 71, 72, 73, 13]
CAT_ANIMALS_PLANTS = [28, 74, 75, 76]
CAT_WINDOWS_DOORS_PANELS = [16, 23, 47]
CAT_WHEELS_TYRES = [29]
CAT_TECHNIC_SPECIAL = [52, 17, 22, 25, 44, 45, 26]
# Never pieces in a pile: sticker sheets, Duplo, non-System, pens and watches.
CAT_NOT_A_PIECE = [58, 4, 77, 78]

PRINTED_PART_NUM_RE = r"(?:pr|pb|pat)\d"
PRINTED_NAME_RE = r"\bprint(?:ed)?\b"
TECHNIC_SPECIAL_NAME_RE = r"differential|shock absorber|motor"
METALLIC_COLOR_RE = r"chrome|metal|pearl|speckle|copper|silver|gold|two-tone"


@dataclass(frozen=True)
class Part:
    part_num: str
    name: str
    cat_id: int


@dataclass
class Catalog:
    csv_dir: Path
    parts: dict[str, Part]
    categories: dict[int, str]
    colors: dict[int, tuple[str, bool]]  # id -> (name, is_trans)
    set_count: Counter[str] = field(default_factory=Counter)  # part_num -> distinct sets
    part_colors: dict[str, set[int]] = field(default_factory=dict)
    pair_qty: Counter[tuple[str, int]] = field(default_factory=Counter)  # pieces over all inventories
    set_total: int = 0

    @property
    def pile_pieces(self) -> int:
        return sum(self.pair_qty.values())


def load_catalog(csv_dir: Path) -> Catalog:
    with open(csv_dir / "part_categories.csv", newline="", encoding="utf-8") as fh:
        categories = {int(r["id"]): r["name"] for r in csv.DictReader(fh)}
    with open(csv_dir / "colors.csv", newline="", encoding="utf-8") as fh:
        colors = {int(r["id"]): (r["name"], r["is_trans"] == "True") for r in csv.DictReader(fh)}
    with open(csv_dir / "parts.csv", newline="", encoding="utf-8") as fh:
        parts = {
            r["part_num"]: Part(r["part_num"], r["name"], int(r["part_cat_id"]))
            for r in csv.DictReader(fh)
        }
    catalog = Catalog(csv_dir, parts, categories, colors)

    # One inventory per set: version 1 only, like the analysis scripts.
    with open(csv_dir / "inventories.csv", newline="", encoding="utf-8") as fh:
        inv_set = {r["id"]: r["set_num"] for r in csv.DictReader(fh) if r["version"] == "1"}
    catalog.set_total = len(set(inv_set.values()))

    part_sets: dict[str, set[str]] = {}
    with open(csv_dir / "inventory_parts.csv", newline="", encoding="utf-8") as fh:
        reader = csv.reader(fh)
        header = next(reader)
        col = {name: idx for idx, name in enumerate(header)}
        i_inv, i_part, i_color, i_qty, i_spare = (
            col["inventory_id"], col["part_num"], col["color_id"], col["quantity"], col["is_spare"],
        )
        for row in reader:
            set_num = inv_set.get(row[i_inv])
            if set_num is None or row[i_spare] == "True":
                continue
            part_num = row[i_part]
            color_id = int(row[i_color])
            part_sets.setdefault(part_num, set()).add(set_num)
            catalog.part_colors.setdefault(part_num, set()).add(color_id)
            catalog.pair_qty[(part_num, color_id)] += int(row[i_qty])
    catalog.set_count = Counter({p: len(s) for p, s in part_sets.items()})
    return catalog


# --- rule construction -------------------------------------------------------

def _cond(rule_id: str, n: int, field_name: str, op: str, value: Any) -> dict[str, Any]:
    return {"id": f"{rule_id}-c{n}", "field": field_name, "op": op, "value": value}


def _rule(
    rule_id: str,
    name: str,
    conditions: list[dict[str, Any]],
    *,
    match_mode: str = "all",
    children: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "id": rule_id,
        "rule_type": "filter",
        "role": "secondary",
        "name": name,
        "match_mode": match_mode,
        "conditions": conditions,
        "children": children or [],
        "disabled": False,
    }


def _category_rule(rule_id: str, name: str, cat_ids: list[int]) -> dict[str, Any]:
    return _rule(rule_id, name, [_cond(rule_id, 1, "category_id", "in", cat_ids)])


def _color_rule(rule_id: str, name: str, catalog: Catalog, color_ids: list[int]) -> dict[str, Any]:
    # The engine claims every listed colour for every matching part, so an
    # unscoped colour rule would emit parts x colours keys for the whole
    # catalogue. Scope it to parts that ship in one of these colours.
    wanted = set(color_ids)
    part_nums = sorted(p for p, cols in catalog.part_colors.items() if cols & wanted and p in catalog.parts)
    return _rule(rule_id, name, [
        _cond(rule_id, 1, "part_num", "in", part_nums),
        _cond(rule_id, 2, "color_id", "in", color_ids),
    ])


def build_rules(catalog: Catalog, *, rare_max_sets: int, price_min: float) -> list[dict[str, Any]]:
    trans_colors = sorted(cid for cid, (_, is_trans) in catalog.colors.items() if is_trans)
    metallic_colors = sorted(
        cid for cid, (name, is_trans) in catalog.colors.items()
        if not is_trans and re.search(METALLIC_COLOR_RE, name, re.IGNORECASE)
    )
    rules = [
        _rule("printed", "Printed parts", [
            _cond("printed", 1, "part_num", "regex", PRINTED_PART_NUM_RE),
            _cond("printed", 2, "name", "regex", PRINTED_NAME_RE),
        ], match_mode="any"),
        _category_rule("minifig-heads", "Minifig heads", CAT_MINIFIG_HEADS),
        _category_rule("minifig-torsos", "Minifig torsos", CAT_MINIFIG_TORSOS),
        _category_rule("minifig-legs", "Minifig legs", CAT_MINIFIG_LEGS),
        _category_rule("minifig-accessories", "Minifig accessories and headgear", CAT_MINIFIG_ACCESSORIES),
        _category_rule("animals-plants", "Animals and plants", CAT_ANIMALS_PLANTS),
        _category_rule("windows-doors-panels", "Windows, doors and panels", CAT_WINDOWS_DOORS_PANELS),
        _color_rule("transparent", "Transparent parts", catalog, trans_colors),
        _color_rule("metallic", "Chrome, metallic and pearl parts", catalog, metallic_colors),
        _category_rule("wheels-tyres", "Wheels and tyres", CAT_WHEELS_TYRES),
        _rule("technic-special", "Technic special (gears, pneumatics, motors, differentials, shocks)", [
            _cond("technic-special", 1, "category_id", "in", CAT_TECHNIC_SPECIAL),
        ], match_mode="any", children=[
            _rule("technic-special-by-name", "Technic part named like a special", [
                _cond("technic-special-by-name", 1, "category_name", "contains", "Technic"),
                _cond("technic-special-by-name", 2, "name", "regex", TECHNIC_SPECIAL_NAME_RE),
            ]),
        ]),
    ]
    claims = simulate(rules, catalog)
    rare = sorted(
        p for p, part in catalog.parts.items()
        if 1 <= catalog.set_count.get(p, 0) < rare_max_sets
        and part.cat_id not in CAT_NOT_A_PIECE
        and (p, None) not in claims
    )
    rules.append(_rule("rare", f"Rare parts (in fewer than {rare_max_sets} sets)", [
        _cond("rare", 1, "part_num", "in", rare),
    ]))
    rules.append(_rule("high-value", f"High-value parts (BrickLink used avg >= {price_min:g})", [
        _cond("high-value", 1, "bl_price_avg", "gte", price_min),
    ]))
    return rules


# --- CSV-side mirror of the rule engine ---------------------------------------
# Same operators and first-claim semantics as
# app/services/profile_engine/rule_engine.generateProfile, restricted to the
# fields the CSVs carry; anything else evaluates to None (never matches).

CSV_FIELDS = frozenset({"category_id", "category_name", "name", "part_num", "color_id"})


def _csv_evaluable(rule: dict[str, Any]) -> bool:
    return all(c["field"] in CSV_FIELDS for c in rule["conditions"]) and all(
        _csv_evaluable(child) for child in rule["children"]
    )


def _field_value(field_name: str, part: Part, catalog: Catalog) -> Any:
    if field_name == "category_id":
        return part.cat_id
    if field_name == "category_name":
        return catalog.categories.get(part.cat_id, "")
    if field_name == "name":
        return part.name
    if field_name == "part_num":
        return part.part_num
    return None


def _predicate(cond: dict[str, Any], part: Part, catalog: Catalog) -> bool:
    actual = _field_value(cond["field"], part, catalog)
    op, value = cond["op"], cond["value"]
    if op == "eq":
        return actual == value
    if op == "neq":
        return actual != value
    if op == "in":
        return actual in value
    if op == "contains":
        return isinstance(actual, str) and value.lower() in actual.lower()
    if op == "regex":
        return isinstance(actual, str) and bool(re.search(value, actual, re.IGNORECASE))
    if op == "gte":
        return actual is not None and actual >= value
    if op == "lte":
        return actual is not None and actual <= value
    return False


def _part_matches(rule: dict[str, Any], part: Part, catalog: Catalog) -> bool:
    results = [
        _predicate(c, part, catalog) for c in rule["conditions"] if c["field"] != "color_id"
    ]
    results += [
        _part_matches(child, part, catalog) for child in rule["children"] if not child.get("disabled")
    ]
    if not results:
        return True
    return (all if rule["match_mode"] == "all" else any)(results)


def _rule_colors(rule: dict[str, Any]) -> set[int] | None:
    colors: set[int] = set()
    found = False
    for c in rule["conditions"]:
        if c["field"] != "color_id":
            continue
        found = True
        if c["op"] == "eq":
            colors.add(c["value"])
        elif c["op"] == "in":
            colors.update(c["value"])
    for child in rule["children"]:
        child_colors = _rule_colors(child)
        if child_colors is not None:
            found = True
            colors |= child_colors
    return colors if found else None


def simulate(rules: list[dict[str, Any]], catalog: Catalog) -> dict[tuple[str, int | None], str]:
    """First-claim pass over the catalogue: (part_num, color_id|None) -> rule id."""
    claims: dict[tuple[str, int | None], str] = {}
    compiled = [(r, _rule_colors(r)) for r in rules if not r.get("disabled")]
    for part_num, part in catalog.parts.items():
        for rule, colors in compiled:
            if not _part_matches(rule, part, catalog):
                continue
            if colors is None:
                claims.setdefault((part_num, None), rule["id"])
                break
            for cid in colors:
                claims.setdefault((part_num, cid), rule["id"])
    return claims


@dataclass
class RuleStats:
    parts_gross: int = 0
    parts_claimed: int = 0
    color_keys: int = 0
    inventory_pairs: int = 0
    pile_pieces: int = 0


def collect_stats(rules: list[dict[str, Any]], catalog: Catalog) -> tuple[dict[str, RuleStats], RuleStats]:
    claims = simulate(rules, catalog)
    stats = {r["id"]: RuleStats() for r in rules}
    for rule in rules:
        stats[rule["id"]].parts_gross = sum(1 for p in catalog.parts.values() if _part_matches(rule, p, catalog))
    for (part_num, color_id), rule_id in claims.items():
        if color_id is None:
            stats[rule_id].parts_claimed += 1
        else:
            stats[rule_id].color_keys += 1
    rest = RuleStats()
    for (part_num, color_id), qty in catalog.pair_qty.items():
        rule_id = claims.get((part_num, color_id)) or claims.get((part_num, None))
        target = stats[rule_id] if rule_id else rest
        target.inventory_pairs += 1
        target.pile_pieces += qty
    return stats, rest


# --- output ------------------------------------------------------------------

def build_payload(rules: list[dict[str, Any]], *, name: str, publish: bool) -> dict[str, Any]:
    return {
        "name": name,
        "description": PROFILE_DESCRIPTION,
        "default_category_id": DEFAULT_CATEGORY_ID,
        "rules": rules,
        "fallback_mode": {"rebrickable_categories": False, "bricklink_categories": False, "by_color": False},
        "change_note": f"generated by scripts/generate_secondary_profile.py on {date.today().isoformat()}",
        "label": None,
        "publish": publish,
    }


def _describe_condition(cond: dict[str, Any], catalog: Catalog) -> str:
    value = cond["value"]
    if cond["op"] == "in":
        if cond["field"] == "category_id":
            value = ", ".join(catalog.categories.get(v, str(v)) for v in value)
        elif cond["field"] == "color_id":
            value = f"{len(value)} colours"
        else:
            value = f"{len(value):,} {cond['field']}s"
        return f"{cond['field']} in [{value}]"
    if cond["op"] == "regex":
        return f"{cond['field']} ~ `{value}`"
    return f"{cond['field']} {cond['op']} {value!r}"


def _describe_rule(rule: dict[str, Any], catalog: Catalog) -> str:
    joiner = " AND " if rule["match_mode"] == "all" else " OR "
    parts = [_describe_condition(c, catalog) for c in rule["conditions"]]
    parts += [f"({_describe_rule(child, catalog)})" for child in rule["children"]]
    return joiner.join(parts)


RULE_NOTES = {
    "printed": "Rebrickable has no print relation in the CSV dump, so printed parts are recognised by the "
               "part number (`pr`/`pb` print suffixes, `pat` dual-moulded patterns) or a `Print` in the name.",
    "minifig-heads": "Minifig and Minidoll head categories. Printed heads were already claimed by the printed rule.",
    "minifig-torsos": "Minifig and Minidoll upper body categories; printed torsos went to the printed rule.",
    "minifig-legs": "Minifig and Minidoll lower body categories.",
    "minifig-accessories": "Accessories, headwear, hip/neck wear, shields, weapons, tools and the legacy Minifigs category.",
    "animals-plants": "Animals, creatures, their body parts and accessories, plants and trees.",
    "windows-doors-panels": "Windows and Doors, Panels, Windscreens and Fuselage.",
    "transparent": "Every Rebrickable colour with is_trans, scoped to parts that ship in a transparent colour "
                   "in at least one inventory (the engine claims parts x colours keys, unscoped that is the "
                   "whole catalogue times every transparent colour).",
    "metallic": f"Colour names matching `{METALLIC_COLOR_RE}` that are not transparent (glitter and opal are "
                "transparent and land in the transparent bin). Scoped like the transparent rule.",
    "wheels-tyres": "Wheels and Tyres category.",
    "technic-special": "Technic Gears, Gear Parts, Pneumatics, Steering/Suspension/Engine, Mechanical, "
                       "Electronics, Technic Special, plus any Technic-category part named differential, "
                       "shock absorber or motor.",
    "rare": "Set counts are not an engine field: the list is baked from the inventories (distinct sets, "
            "version-1 inventories, spares ignored). Parts already claimed by an earlier rule and non-piece "
            "categories (Stickers, Duplo, Non-System, Pen & Watch) are left out; parts that never shipped in "
            "a set are left out too. Regenerate after a CSV refresh.",
    "high-value": "Uses the engine's BrickLink price guide (ord_used average, inv_used fallback, most liquid "
                  "colour per item). The CSVs carry no prices, so no count here; the rule only matches on a "
                  "Hive whose parts cache has synced prices (POST /api/profile-catalog/sync/prices).",
}

NOT_EXPRESSIBLE = [
    "Rarity (sets a part appears in): no engine field, baked as a `part_num in [...]` list.",
    "Print relation: Rebrickable's parent/child print relationships are not in the dump and the engine has "
    "no decorated flag; part-number and name patterns approximate it.",
    "Per-part colour availability: the engine claims every listed colour for every matching part, so colour "
    "rules produce a parts x colours cross product; scoping the part list keeps the artifact small.",
    "Per-colour prices: the engine sees one representative price row per BrickLink item, not per colour.",
    "Negation (`not in`): the rare list is materialised instead of excluding common parts.",
]


def render_summary(
    rules: list[dict[str, Any]],
    catalog: Catalog,
    stats: dict[str, RuleStats],
    rest: RuleStats,
    *,
    rare_max_sets: int,
    price_min: float,
) -> str:
    pile = catalog.pile_pieces or 1
    lines = [
        f"# {PROFILE_NAME}: secondary profile summary",
        "",
        f"Generated {date.today().isoformat()} from `{catalog.csv_dir}`: {len(catalog.parts):,} parts, "
        f"{len(catalog.colors)} colours, {catalog.set_total:,} sets with a version-1 inventory, "
        f"{catalog.pile_pieces:,} inventory pieces. Parameters: rare-max-sets={rare_max_sets}, "
        f"price-min={price_min:g}.",
        "",
        "Rules in bin-priority order; the first matching rule claims a part (or a part/colour pair for "
        "colour rules). Counts are from the CSVs, so they say nothing about BrickLink-only fields.",
        "",
        "| # | Rule | Expression | Parts matching | Parts claimed | Colour keys | Inventory pairs | Pile share |",
        "|---|------|------------|---------------:|--------------:|------------:|----------------:|-----------:|",
    ]
    for idx, rule in enumerate(rules, start=1):
        s = stats[rule["id"]]
        if _csv_evaluable(rule):
            counts = (f"{s.parts_gross:,} | {s.parts_claimed:,} | {s.color_keys:,} | {s.inventory_pairs:,} | "
                      f"{100 * s.pile_pieces / pile:.1f}%")
        else:
            counts = "n/a | n/a | n/a | n/a | n/a"
        lines.append(f"| {idx} | {rule['name']} (`{rule['id']}`) | {_describe_rule(rule, catalog)} | {counts} |")
    lines.append(
        f"| | Pass-through (`{DEFAULT_CATEGORY_ID}`) | no rule matched | | | | "
        f"{rest.inventory_pairs:,} | {100 * rest.pile_pieces / pile:.1f}% |"
    )
    lines += ["", "## Rule notes", ""]
    for rule in rules:
        lines.append(f"- **{rule['name']}** (`{rule['id']}`): {RULE_NOTES[rule['id']]}")
    lines += ["", "## Not expressible in the rule engine", ""]
    lines += [f"- {item}" for item in NOT_EXPRESSIBLE]
    lines += [
        "",
        "## Import",
        "",
        "`POST /api/profiles` to create the profile, then `POST /api/profiles/{id}/versions` with the "
        "generated JSON as the body (cookie session plus `X-CSRF-Token`). `POST /api/profiles/preview` "
        "dry-runs the same document.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("csv_dir", type=Path, help="directory with the Rebrickable CSVs")
    parser.add_argument("--out", type=Path, default=Path("seltenes-und-besonderes.json"),
                        help="profile JSON (default: %(default)s)")
    parser.add_argument("--summary", type=Path, default=None,
                        help="markdown summary (default: <out>.md)")
    parser.add_argument("--name", default=PROFILE_NAME, help="profile name (default: %(default)s)")
    parser.add_argument("--rare-max-sets", type=int, default=20,
                        help="a part is rare below this many sets (default: %(default)s)")
    parser.add_argument("--price-min", type=float, default=2.0,
                        help="bl_price_avg threshold for the high-value rule (default: %(default)s)")
    parser.add_argument("--no-publish", action="store_true", help="emit publish: false")
    args = parser.parse_args(argv)
    summary_path = args.summary or args.out.with_suffix(".md")

    catalog = load_catalog(args.csv_dir)
    rules = build_rules(catalog, rare_max_sets=args.rare_max_sets, price_min=args.price_min)
    stats, rest = collect_stats(rules, catalog)

    payload = build_payload(rules, name=args.name, publish=not args.no_publish)
    args.out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    summary_path.write_text(
        render_summary(rules, catalog, stats, rest, rare_max_sets=args.rare_max_sets, price_min=args.price_min),
        encoding="utf-8",
    )
    print(f"wrote {args.out} ({len(rules)} rules) and {summary_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
