services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sorthive
      POSTGRES_PASSWORD: sorthive_dev
      POSTGRES_DB: sorthive
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres

volumes:
  pgdata:
