CREATE TABLE price_guides (
    item_no TEXT PRIMARY KEY REFERENCES bricklink_items(item_no),
    updated_at TEXT,
    inv_new_lots INTEGER DEFAULT 0,
    inv_new_qty INTEGER DEFAULT 0,
    inv_new_min REAL,
    inv_new_max REAL,
    inv_new_avg REAL,
    inv_new_wavg REAL,
    inv_used_lots INTEGER DEFAULT 0,
    inv_used_qty INTEGER DEFAULT 0,
    inv_used_min REAL,
    inv_used_max REAL,
    inv_used_avg REAL,
    inv_used_wavg REAL,
    ord_new_lots INTEGER DEFAULT 0,
    ord_new_qty INTEGER DEFAULT 0,
    ord_new_min REAL,
    ord_new_max REAL,
    ord_new_avg REAL,
    ord_new_wavg REAL,
    ord_used_lots INTEGER DEFAULT 0,
    ord_used_qty INTEGER DEFAULT 0,
    ord_used_min REAL,
    ord_used_max REAL,
    ord_used_avg REAL,
    ord_used_wavg REAL
);
