"""initial schema

Revision ID: 0f3b104c89eb
Revises: 
Create Date: 2026-04-01 10:56:12.755057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f3b104c89eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('member', 'reviewer', 'admin')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('machines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_prefix', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hardware_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_machines_owner_id', 'machines', ['owner_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('upload_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('source_session_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_upload_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'source_session_id', name='uq_upload_sessions_machine_source')
    )
    op.create_index('ix_upload_sessions_machine_id', 'upload_sessions', ['machine_id'], unique=False)
    op.create_table('samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=False),
    sa.Column('upload_session_id', sa.UUID(), nullable=False),
    sa.Column('local_sample_id', sa.String(), nullable=False),
    sa.Column('source_role', sa.String(), nullable=True),
    sa.Column('capture_reason', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('full_frame_path', sa.String(), nullable=True),
    sa.Column('overlay_path', sa.String(), nullable=True),
    sa.Column('image_width', sa.Integer(), nullable=True),
    sa.Column('image_height', sa.Integer(), nullable=True),
    sa.Column('detection_algorithm', sa.String(), nullable=True),
    sa.Column('detection_bboxes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detection_count', sa.Integer(), nullable=True),
    sa.Column('detection_score', sa.Float(), nullable=True),
    sa.Column('review_status', sa.String(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("review_status IN ('unreviewed', 'in_review', 'accepted', 'rejected', 'conflict')", name='ck_samples_review_status'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_session_id'], ['upload_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('upload_session_id', 'local_sample_id', name='uq_samples_session_local')
    )
    op.create_index('ix_samples_machine_id', 'samples', ['machine_id'], unique=False)
    op.create_index('ix_samples_review_status', 'samples', ['review_status'], unique=False)
    op.create_index('ix_samples_source_role', 'samples', ['source_role'], unique=False)
    op.create_index('ix_samples_upload_session_id', 'samples', ['upload_session_id'], unique=False)
    op.create_index('ix_samples_uploaded_at', 'samples', ['uploaded_at'], unique=False)
    op.create_table('sample_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("decision IN ('accept', 'reject')", name='ck_sample_reviews_decision'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sample_id', 'reviewer_id', name='uq_sample_reviews_sample_reviewer')
    )
    op.create_index('ix_sample_reviews_reviewer_id', 'sample_reviews', ['reviewer_id'], unique=False)
    op.create_index('ix_sample_reviews_sample_id', 'sample_reviews', ['sample_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sample_reviews_sample_id', table_name='sample_reviews')
    op.drop_index('ix_sample_reviews_reviewer_id', table_name='sample_reviews')
    op.drop_table('sample_reviews')
    op.drop_index('ix_samples_uploaded_at', table_name='samples')
    op.drop_index('ix_samples_upload_session_id', table_name='samples')
    op.drop_index('ix_samples_source_role', table_name='samples')
    op.drop_index('ix_samples_review_status', table_name='samples')
    op.drop_index('ix_samples_machine_id', table_name='samples')
    op.drop_table('samples')
    op.drop_index('ix_upload_sessions_machine_id', table_name='upload_sessions')
    op.drop_table('upload_sessions')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_machines_owner_id', table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
