"""Add last_seen_ip and local_ui_port to machines

Revision ID: 698e3443e16a
Revises: a1b2c3d4e5f6
Create Date: 2026-04-05 11:30:52.204362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '698e3443e16a'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('machines', sa.Column('last_seen_ip', sa.String(), nullable=True))
    op.add_column('machines', sa.Column('local_ui_port', sa.String(), nullable=True))
    op.drop_column('sorting_profile_versions', 'set_config_json')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorting_profile_versions', sa.Column('set_config_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('machines', 'local_ui_port')
    op.drop_column('machines', 'last_seen_ip')
    # ### end Alembic commands ###
